import { dbPromise } from "../database.js";
export const PERSONAS=["Default","Pirate","Teacher","Chill","Detective","Space Captain","Coach","Storyteller","Programmer","Scholar","Comedian","Custom"] as const;export type Persona=typeof PERSONAS[number];export type ResponseLength="Short"|"Medium"|"Detailed";export type SafetyLevel="Strict"|"Balanced"|"Relaxed";export type Provider="gemini"|"groq"|"openrouter";export interface Settings{user_id:string;guild_id:string;custom_system_prompt:string;custom_persona:string;persona:Persona;response_length:ResponseLength;safety_level:SafetyLevel;provider:Provider;model:string;vip:number}
const defaults={custom_system_prompt:"",custom_persona:"",persona:"Default",response_length:"Medium",safety_level:"Balanced",provider:"gemini",model:"gemini-3.6-flash",vip:0} as const;
export async function getSettings(u:string,g?:string):Promise<Settings>{const db=await dbPromise,s=g??"",r=await db.get<Settings>("SELECT * FROM user_settings WHERE user_id=? AND guild_id=?",u,s);if(r)return r;const v=s?(await db.get<any>("SELECT vip FROM user_settings WHERE user_id=? AND guild_id=''",u))?.vip??0:0;await db.run("INSERT INTO user_settings(user_id,guild_id,vip,updated_at) VALUES(?,?,?,?)",u,s,v,Date.now());return{user_id:u,guild_id:s,...defaults,vip:v}}
export async function updateSettings(u:string,g:string|undefined,c:Partial<Pick<Settings,"custom_system_prompt"|"custom_persona"|"persona"|"response_length"|"safety_level"|"provider"|"model">>){const db=await dbPromise,s=g??"";await getSettings(u,s);const e=Object.entries(c);if(e.length)await db.run(`UPDATE user_settings SET ${e.map(([k])=>k+"=?").join(",")},updated_at=? WHERE user_id=? AND guild_id=?`,...e.map(([,v])=>v),Date.now(),u,s)}
export async function resetSettings(u:string,g?:string){await updateSettings(u,g,{custom_system_prompt:"",custom_persona:"",persona:"Default",response_length:"Medium",safety_level:"Balanced",provider:"gemini",model:"gemini-3.6-flash"})}
export async function setVip(u:string,v:boolean){const db=await dbPromise;await db.run("INSERT INTO user_settings(user_id,guild_id,vip,updated_at) VALUES(?,'',?,?) ON CONFLICT(user_id,guild_id) DO UPDATE SET vip=excluded.vip,updated_at=excluded.updated_at",u,v?1:0,Date.now());await db.run("UPDATE user_settings SET vip=?,updated_at=? WHERE user_id=?",v?1:0,Date.now(),u)}
export async function setUserBlacklist(u:string,v:boolean){const db=await dbPromise;await db.run("INSERT INTO user_settings(user_id,guild_id,blacklisted,updated_at) VALUES(?,'',?,?) ON CONFLICT(user_id,guild_id) DO UPDATE SET blacklisted=excluded.blacklisted,updated_at=excluded.updated_at",u,v?1:0,Date.now());await db.run("UPDATE user_settings SET blacklisted=?,updated_at=? WHERE user_id=?",v?1:0,Date.now(),u)}
export async function isUserBlacklisted(u:string):Promise<boolean>{const db=await dbPromise;const row=await db.get<{ blacklisted: number }>("SELECT blacklisted FROM user_settings WHERE user_id=? AND guild_id=''",u);return Boolean(row?.blacklisted);} 
export async function deleteUserDataExceptVip(u:string){const db=await dbPromise;await db.run("DELETE FROM conversations WHERE user_id=?",u);await db.run("DELETE FROM prompt_events WHERE user_id=?",u);await db.run("DELETE FROM response_metrics WHERE user_id=?",u);await db.run("DELETE FROM quota_violations WHERE user_id=?",u);await db.run("UPDATE user_settings SET custom_system_prompt='',custom_persona='',persona='Default',response_length='Medium',safety_level='Balanced',provider='gemini',model='gemini-3.6-flash',blacklisted=0,updated_at=? WHERE user_id=?",Date.now(),u)}
